name: SimpleMCTiers
version: '2.0'
main: vadlox.dev.simpleMCTiers.SimpleMCTiers
api-version: '1.21'
description: The Ultimate Clans Plugin.
website: vadlox.hydraquest.net
depend: [ PlaceholderAPI ]
authors:
  - Vadlox
commands:
  tier:
    description: Get the tier of a player.
    permission: simplemctiers.tier
    permission-message: You do not have permission to use this command.
permissions:
  simplemctiers.tier:
    description: Allows the use of the /tier command
    default: true
