name: SimpleMCTiers
version: '2.0'
main: vadlox.dev.simpleMCTiers.SimpleMCTiers
api-version: '1.21'
description: The Ultimate Tiers Plugin.
website: vadlox.hydraquest.net
depend: [ PlaceholderAPI ]
authors:
  - Vadlox

commands:
  tier:
    description: Get the tier of a player in a specific gamemode.
    permission: simplemctiers.tier

  simplemctiers:
    description: Admin tool for SimpleMCTiers overrides.
    permission: simplemctiers.admin

permissions:
  simplemctiers.tier:
    description: Allows use of the /tier command
    default: true

  simplemctiers.admin:
    description: Allows management of overrides via /simplemctiers
    default: op
